# ---------------------------
# Used work tags :
# - `worker` for common jobs
# - `cd-worker` for image pack, deploy, restart svcs
#
# ENV from Gitlab
# - NPM_REGISTRY for pull
# - NPM_VERSION_REGISTRY for npm publish, equal to version.registry of lerna.json (if exists)
# ---------------------------


include:
  - local: '/.scripts/cd/.gitlab-cd.yml'
  - local: '/.scripts/stages/build.yml'
  - local: '/.scripts/stages/pre_release.yml'

stages:
  - build
  - testing
  - rc-pack
  - pre-release  # create release branch
  - pre-publish
  - publish
  - pack
  - deploy
  - post-deploy

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 50

  # for branches except version tag
  PACK_DEV_TAR: ""
  PACK_DEV_IMG: ""
  # only for master and release branches
  PACK_RC_TAR: ""
  PACK_RC_IMG: ""
  # only for version tag
  PACK_GA_TAR: ""
  PACK_GA_IMG: "yes"
  TAR_COMPRESSION_LEVEL: 7
  IMG_COMPRESSION_LEVEL: 4
  ZSTD_CLEVEL: 11

  PUB_AS_BETA: "yes"
  PUB_AS_BETA_MAJOR: ""
  PUB_AS_BETA_MAJOR: ""
  PUB_AS_LATEST: "yes"
  PUB_AS_LATEST_MAJOR: ""
  PUB_AS_NEXT: ""
  PUB_AS_NEXT_MAJOR: ""

  # for pull
  #NPM_REGISTRY: https://nexus.foo.com/repository/npm-central/
  # for npm publish, equal to version.registry of lerna.json (if exists)
  #NPM_VERSION_REGISTRY: https://nexus.foo.com/repository/mynpm/
  NPM_DIST: https://npm.taobao.org/dist
  # restrict branch for version, equal to  version.allowBranch of lerna.json
  RELEASE_BRANCH: release
  BUILD_TMP_DIR: /tmp/build

  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: db_ci_mw
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust

  REDIS_HOST: redis
  REDIS_PORT: 6379


default:
  image: $NODE_CI_IMAGE
  before_script:
    - echo -e "\e[0Ksection_start:`date +%s`:before_script_section[collapsed=true]\r\e[0K Prepare"
    - echo $SHELL
    - echo $CI_SERVER_VERSION
    - echo "$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME"
    - echo $CI_COMMIT_REF_SLUG
    - echo "$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"
    - echo "$CI_PIPELINE_ID:$CI_JOB_ID"
    - echo $GITLAB_USER_LOGIN
    - npm config set registry "$NPM_REGISTRY"
    - npm config set disturl "$NPM_DIST"
    - npm root -g
    - node -v
    - npm -v
    - free -m
    - df -hT
    - du -sh *
    - sh .scripts/util/check-env.sh
    - sh .scripts/ci/ci-prepare.sh
    - source .scripts/util/import-myca.sh
    - echo -e "\e[0Ksection_end:`date +%s`:before_script_section\r\e[0K"
  after_script:
    - sh .scripts/ci/after_script.sh
  cache: &global_cache
    key: cache_dev
    paths:
      - node_modules
    policy: pull
  services:
  - name: $PG_IMAGE
    alias: postgres
  - name: $REDIS_IMAGE
    alias: redis



.rc-pack:
  stage: rc-pack
  tags:
    - worker
  artifacts:
    expire_in: '7 day'
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$(date +%Y-%m-%d.%H_%M_%S)-$CI_COMMIT_SHORT_SHA"
    paths:
      - assets/
  script:
    - sh .scripts/ci/ci-commitlint.sh
    - echo -e "\e[0Ksection_start:`date +%s`:build_section[collapsed=true]\r\e[0K Build"
    - npm run bootstrap
    - npm run build
    - echo -e "\e[0Ksection_end:`date +%s`:build_section\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:ci_section[collapsed=true]\r\e[0K CI"
    - npm run lint:nofix
    - echo -e "\e[0Ksection_end:`date +%s`:ci_section\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:pack_section[collapsed=true]\r\e[0K Pack"
    - npm run tar
    - echo -e "\e[0Ksection_end:`date +%s`:pack_section\r\e[0K"
  when: manual

tar_dev:
  extends: .rc-pack
  only:
    refs:
      - branches
    variables:
      - $PACK_DEV_TAR == "yes"
  except:
    - master
    - /^release.*/
    - /^v\d+(\.\d+){2}.*/

tar_rc:
  extends: .rc-pack
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
      - $CI_COMMIT_REF_NAME == $RELEASE_BRANCH
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
      - $PACK_RC_TAR != "yes"
  cache:
    <<: *global_cache
    key: cache_release


.build-image:
  image: $NODE_DOCKER_IMAGE
  tags:
    # - worker
    # should running on dedicated worker
    - cd-worker
  cache:
    <<: *global_cache
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:build_section[collapsed=true]\r\e[0K Build"
    - npm run bootstrap
    - npm run build
    - echo -e "\e[0Ksection_end:`date +%s`:build_section\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:ci_section[collapsed=true]\r\e[0K CI"
    - npm run lint:nofix
    - echo -e "\e[0Ksection_end:`date +%s`:ci_section\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:build_image_section[collapsed=true]\r\e[0K Build Image"
    - sh .scripts/build-images.sh
    - echo -e "\e[0Ksection_end:`date +%s`:build_image_section\r\e[0K"
    - free -m
  when: manual

image_dev:
  extends: .build-image
  stage: rc-pack
  only:
    refs:
      - branches
    variables:
      - $PACK_DEV_IMG == "yes"
  except:
    - master
    - /^release.*/
    - /^v\d+(\.\d+){2}.*/

image_rc:
  extends: .build-image
  stage: rc-pack
  only:
    refs:
      # - master
      - /^release.*/
    variables:
      - $PACK_RC_IMG == "yes"
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  cache:
    <<: *global_cache
    key: cache_release


.publish:
  stage: publish
  tags:
    # - worker
    # should running on dedicated worker
    - cd-worker
  cache:
    <<: *global_cache
    key: cache_release
    policy: pull-push
  variables:
    GIT_STRATEGY: clone
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $RELEASE_BRANCH
  allow_failure: false
  # $GITLAB_USER_NAME will be deploy name if auto,
  # and be the user of running the job if manual
  when: manual

# npm with latest
publish_latest:
  extends: .publish
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish Latest"
    # workaround for preversion and prepack of pkg.scripts
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"
  except:
    variables:
      - $PUB_AS_LATEST != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/

publish_latest_major:
  extends: .publish
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish major"
    # workaround for preversion and prepack of pkg.scripts
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab major
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"
  except:
    variables:
      - $PUB_AS_LATEST_MAJOR != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/

# npm with beta
publish_beta:
  extends: .publish
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish Beta"
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab --dist-tag beta --force-publish=*
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"
  except:
    variables:
      - $PUB_AS_BETA != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  allow_failure: true

# npm with beta
publish_beta_major:
  extends: .publish
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish Beta major"
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab --dist-tag beta --force-publish=* major
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"
  except:
    variables:
      - $PUB_AS_BETA_MAJOR != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  allow_failure: true

# npm with next
publish_next:
  extends: .publish
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish Next"
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab --dist-tag next
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"
  except:
    variables:
      - $PUB_AS_NEXT != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  allow_failure: true

# npm with next major
publish_next_major:
  extends: .publish
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish Next major"
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab --dist-tag next major
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"
  except:
    variables:
      - $PUB_AS_NEXT_MAJOR != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  allow_failure: true

tar_ga:
  stage: pack
  tags:
    - worker
  only:
    refs:
      - /^v\d+(\.\d+){2}.*/
    variables:
      - $PACK_GA_TAR == "yes"
  except:
    refs:
      - branches
    variables:
      - $CI_PUBLISH_COMPLETED != "true"
  artifacts:
    expire_in: '1 month'
    name: "$CI_PROJECT_NAME-$CI_COMMIT_TAG-$(date +%Y-%m-%d.%H_%M_%S)-$CI_COMMIT_SHORT_SHA"
    paths:
      - assets/
  cache: {}
  when: delayed
  start_in: 5 seconds
  script:
    - npm run tar


image_ga:
  extends: .build-image
  stage: pack
  only:
    - /^v\d+(\.\d+){2}.*/
  except:
    refs:
      - branches
    variables:
      - $PACK_GA_IMG != "yes"
      - $CI_PUBLISH_COMPLETED != "true"
  cache: {}
  when: delayed
  start_in: 5 seconds
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:image_ga_section[collapsed=true]\r\e[0K Image GA"
    - sh .scripts/build-images.sh
    - echo -e "\e[0Ksection_end:`date +%s`:image_ga_section\r\e[0K"

