# ---------------------------
# Used work tags :
# - `worker` for common jobs
# - `cd-worker` for image pack, distribute, deploy, restart svcs
#
# ENV from Gitlab
# - NPM_REGISTRY for pull
# - NPM_VERSION_REGISTRY for npm publish, equal to version.registry of lerna.json (if exists)
# ---------------------------


include:
  - local: '/.scripts/stages/build.yml'
  - local: '/.scripts/stages/pre_release.yml'
  - local: '/.scripts/stages/pack.yml'
  - local: '/.scripts/stages/dist.yml'
  - local: '/.scripts/stages/post-deploy.yml'

stages:
  - build
  - testing
  - rc-pack
  - pre-release  # create release branch
  - pre-publish
  - publish
  - pack
  - distribute
  - deploy
  - post-deploy

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 50

  # for branches except version tag
  PACK_DEV_IMG: ""
  # only for main and release branches
  PACK_RC_IMG: ""
  # only for version tag
  PACK_GA_IMG: "yes"
  TAR_COMPRESSION_LEVEL: 7
  IMG_COMPRESSION_LEVEL: 4
  ZSTD_CLEVEL: 11

  PUB_AS_BETA: ""
  PUB_AS_BETA_MAJOR: ""
  PUB_AS_BETA_MAJOR: ""
  PUB_AS_LATEST: "yes"
  PUB_AS_LATEST_MAJOR: ""
  PUB_AS_NEXT: ""
  PUB_AS_NEXT_MAJOR: ""

  # for pull
  #NPM_REGISTRY: https://nexus.foo.com/repository/npm-central/
  # for npm publish, equal to version.registry of lerna.json (if exists)
  #NPM_VERSION_REGISTRY: https://nexus.foo.com/repository/mynpm/
  NPM_DIST: https://npm.taobao.org/dist
  # restrict branch for version, equal to  version.allowBranch of lerna.json
  RELEASE_BRANCH: release
  BUILD_TMP_DIR: /tmp/build
  BUILD_LOCKS_CACHE_DIR: locks-cache

  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_DB: db_ci_mw
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust

  REDIS_HOST: redis
  REDIS_PORT: 6379


default:
  image: $NODE_CI_IMAGE
  before_script:
    - echo $CI_JOB_STARTED_AT
    - echo -e "\e[0Ksection_start:`date +%s`:before_script_section[collapsed=true]\r\e[0K Prepare"
    - echo $SHELL
    - echo $CI_SERVER_VERSION
    - echo $CI_PROJECT_URL
    - echo "$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME"
    - echo $CI_COMMIT_REF_SLUG
    - echo $CI_COMMIT_BRANCH
    - echo "$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"
    - echo "$CI_PIPELINE_ID:$CI_JOB_ID"
    - echo $GITLAB_USER_LOGIN
    - npm config set registry "$NPM_REGISTRY"
    - npm config set disturl "$NPM_DIST"
    - npm root -g
    - node -v
    - npm -v
    - free -m
    - df -hT
    - ls -l
    - du -sh packages/*
    - export cwd=`pwd`
    - source .scripts/util/alias.sh
    - sh .scripts/util/check-env.sh
    - source .scripts/ci/ci-prepare.sh
    - source .scripts/util/import-myca.sh
    - echo -e "\e[0Ksection_end:`date +%s`:before_script_section\r\e[0K"
  after_script:
    - export cwd=`pwd`
    - sh .scripts/ci/after_script.sh
  cache: &global_cache
    key: cache_dev
    paths:
      - node_modules
      - package-lock.json
    policy: pull-push
  services:
  - name: $PG_IMAGE
    alias: postgres
  # - name: $REDIS_IMAGE
  #   alias: redis


.publish:
  stage: publish
  tags:
    - cd-worker
  cache:
    <<: *global_cache
    key: cache_release
    policy: pull
  variables:
    GIT_STRATEGY: clone
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $RELEASE_BRANCH
  allow_failure: false
  # $GITLAB_USER_NAME will be deploy name if auto,
  # and be the user of running the job if manual
  when: manual

# npm with latest
publish_latest:
  extends: .publish
  except:
    variables:
      - $PUB_AS_LATEST != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish Latest"
    # workaround for preversion and prepack of pkg.scripts
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"


publish_latest_major:
  extends: .publish
  except:
    variables:
      - $PUB_AS_LATEST_MAJOR != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish major"
    # workaround for preversion and prepack of pkg.scripts
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab major
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"

# npm with beta
publish_beta:
  extends: .publish
  except:
    variables:
      - $PUB_AS_BETA != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  allow_failure: true
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish Beta"
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab --dist-tag beta --force-publish=*
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"

# npm with beta
publish_beta_major:
  extends: .publish
  except:
    variables:
      - $PUB_AS_BETA_MAJOR != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  allow_failure: true
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish Beta major"
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab --dist-tag beta --force-publish=* major
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"

# npm with next
publish_next:
  extends: .publish
  except:
    variables:
      - $PUB_AS_NEXT != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  allow_failure: true
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish Next"
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab --dist-tag next
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"

# npm with next major
publish_next_major:
  extends: .publish
  except:
    variables:
      - $PUB_AS_NEXT_MAJOR != "yes"
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  allow_failure: true
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:publish_section[collapsed=true]\r\e[0K Publish Next major"
    - echo "unsafe-perm = true" >> ~/.npmrc
    - bash .scripts/ci/ci-publish.sh --loglevel $PUB_LOG_LEVEL --conventional-commits --create-release gitlab --dist-tag next major
    - echo -e "\e[0Ksection_end:`date +%s`:publish_section\r\e[0K"

