
bail: true
full-trace: true
enable-source-maps: true
require:
  - ts-node/register
  - tsconfig-paths/register
  - test/root.hooks.ts
spec:
  - test/**/*.test.ts
timeout: 360000
ui: bdd
parallel: true
exit: true

