
.build:
  stage: build
  tags:
    - worker
  variables:
    GIT_DEPTH: 20
  script:
    - echo -e "\e[0Ksection_start:`date +%s`:build_section[collapsed=true]\r\e[0K Build"
    - date
    - npm run bootstrap -- --no-ci
    - date
    - sh .scripts/ci/ci-commitlint.sh
    - npm run build
    - ls -al
    - echo -e "\e[0Ksection_end:`date +%s`:build_section\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:init_db_section[collapsed=true]\r\e[0K Init database"
    - sh .scripts/ci/ci-init-db.sh
    - echo -e "\e[0Ksection_end:`date +%s`:init_db_section\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:ci_section[collapsed=true]\r\e[0K CI"
    # lint must after build for mono-repo
    #- lerna run lint:nofix # will fail under lerna4
    - npm run lint:nofix
    - npm run ci
    - echo -e "\e[0Ksection_end:`date +%s`:ci_section\r\e[0K"
    - echo -e "\e[0Ksection_start:`date +%s`:cov_section[collapsed=true]\r\e[0K Coverage"
    - sh .scripts/collect-coverages.sh
    - echo -e "\e[0Ksection_end:`date +%s`:cov_section\r\e[0K"
  artifacts:
    expire_in: '14 day'
    reports:
      cobertura: coverage/cobertura-coverage.xml
    paths:
      - coverage/

build_dev:
  extends: .build
  except:
    - main
    - master
    - /^release.*/
    - /^v\d+(\.\d+){2}.*/
  cache:
    key: cache_dev
    paths:
      - node_modules
      - package-lock.json
    policy: pull-push

build_rc:
  extends: .build
  only:
    - main
    - master
    - /^release.*/
  except:
    variables:
      # no tag merging
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
  cache:
    key: cache_release
    paths:
      - node_modules
      - package-lock.json
    policy: pull-push
  artifacts:
    expire_in: '30 day'
    reports:
      cobertura: coverage/cobertura-coverage.xml
    paths:
      - coverage/


