
.build:
  stage: build
  tags:
    - worker
  # cache: {}
  needs:
    - analysis
  script:
    - date
    - echo -e "\e[0Ksection_start:`date +%s`:deps_section[collapsed=true]\r\e[0K Install Deps"
    - npm i --disturl=https://npmmirror.com/dist/
    - echo -e "\e[0Ksection_end:`date +%s`:deps_section\r\e[0K"

    - date
    - .scripts/ci/ci-commitlint.sh

    - date
    - echo -e "\e[0Ksection_start:`date +%s`:build_section[collapsed=true]\r\e[0K Build"
    - npm run build
    - ls -al
    - echo -e "\e[0Ksection_end:`date +%s`:build_section\r\e[0K"

    - date
  allow_failure: false
  artifacts:
    expire_in: '14 day'


build:
  extends: .build
  # only:
  #   - main
  #   - master
  #   - /^release.*/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^v\d+(\.\d+){2}.*/
      - $CI_COMMIT_BRANCH =~ /^versioning_.+/
  artifacts:
    expire_in: '30 day'


