
default:
  image: $NODE_CI_IMAGE
  before_script:
    - echo $CI_JOB_STARTED_AT
    - echo -e "\e[0Ksection_start:`date +%s`:before_script_section[collapsed=true]\r\e[0K Prepare"
    - echo $SHELL
    - echo $CI_SERVER_VERSION
    - echo $CI_PROJECT_URL
    - echo "$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME"
    - echo $CI_COMMIT_REF_SLUG
    - echo $CI_COMMIT_BRANCH
    - echo "$CI_COMMIT_TAG-$CI_COMMIT_SHORT_SHA"
    - echo "$CI_PIPELINE_ID:$CI_JOB_ID"
    - echo $GITLAB_USER_LOGIN
    - export cwd=`pwd`
    - source .scripts/ci/before_script.sh
    - echo -e "\e[0Ksection_end:`date +%s`:before_script_section\r\e[0K"
  after_script:
    - export cwd=`pwd`
    - sh .scripts/ci/after_script.sh
  # cache: &global_cache
  #   key: cache_dev
  #   paths:
  #     - node_modules
  #     - package-lock.json
  #   policy: pull-push
  services:
  - name: $PG_IMAGE
    alias: postgres
  # - name: $REDIS_IMAGE
  #   alias: redis

