# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    # branches-ignore:
    #   - release
    # tags-ignore:
    #   - v*
  pull_request:
    # branches-ignore:
    #   - release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: node:14-buster

    strategy:
      matrix:
        node: [14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache
        uses: actions/cache@v2
        id: cache-lerna
        env:
          cache-name: cache-lerna
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-build-${{ env.cache-name }}-${{ github.ref }}-${{ hashFiles('**/lockfiles') }}
      - name: Verify
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get -qq -y update > /dev/null
          apt-get -qq -y install dnsutils jq net-tools > /dev/null
          uname -a
          apt-get -qq -y install lsb-release > /dev/null
          lsb_release -cs
          sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
          # update again for pg13
          apt-get -qq -y update > /dev/null
          apt-get -qq -y install postgresql-client > /dev/null
          psql -V
          netstat -tunpl
          dig postgres
          echo "\l" | psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U$POSTGRES_USER -d postgres
          psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U$POSTGRES_USER -d $POSTGRES_DB -1 -bq -f ./packages/demo-service/src/database/init.sql
          psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U$POSTGRES_USER -d $POSTGRES_DB -c "\d+"
          psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U$POSTGRES_USER -d $POSTGRES_DB -c "SELECT * FROM tb_user"
        env:
          CI: true
          # use `localhost` if running the job on the VM
          # use `postgres` if running the job on in a container
          POSTGRES_HOST: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          POSTGRES_DB: db_ci_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          PGPASSWORD: postgres
      - name: npm build
        run: |
          openssl version
          node -v
          npm i -g c8 lerna rollup
          npm run bootstrap
          npm run build --if-present
      - name: npm ci
        run: |
          # lint must after build
          npm run lint:s
          npm run ci
        env:
          CI: true
          # pgsql
          # use `localhost` if running the job on the VM
          # use `postgres` if running the job on in a container
          POSTGRES_HOST: postgres
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          POSTGRES_DB: db_ci_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          PGPASSWORD: postgres
          # redis
          REDIS_HOST: redis
          REDIS_PORT: 6379
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1


    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: db_ci_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

